DAppNode incentive
gnosischain/gbc-deposit-ui pull request #1
Opened 2022-01-10 11:04 UTC by pablomendezroyo

## DAppNode incentive
The main purpose of this PR is to add a new tab for DAppNode users that are part of the incentive program promoted by Gnosis. This incentive program is to validate in Gnosis xDAI chain with 4 validators per DAppNode.

The DAppNode tab added contains the same code as in the deposit tab but with a few modifications in the header and the deposit requirements. 

Overall, the DAppNode deposit calls a [SC developed by DAppNode](https://blockscout.com/xdai/mainnet/address/0x6C68322cf55f5f025F2aebd93a28761182d077c3/contracts) that contains a whitelist of address, and under the hoods call the deposit SC of Gnosis.

All the changes implemented in this PR aims to follow the same code standards in the gnosischain/gbc-deposit-ui repository

### DAppNode deposit requirements
- The DAppNode deposit must be called with a "whitelisted" address that has not expired
- The DAppNode deposit must be called with an uploaded `deposit_data.json` with exactly 4 validators

### Other changes
- CI to deploy in gh-pages
- New icon for "wrong" status

2022-01-10 14:47 UTC, maxaleks commented
@pablomendezroyo, thanks for contribution!

Could you undo the changes made for GitHub Pages? We don't need it in this app.

I also think that it would be better to use the `useDeposit` hook inside your `useDappNodeDeposit` hook instead of duplicating the code

2022-01-10 14:48 UTC, maxaleks requested changes
@pablomendezroyo, thanks for contribution!

Could you undo the changes made for GitHub Pages? We don't need it in this app.

I also think that it would be better to use the useDeposit hook inside your useDappNodeDeposit hook instead of duplicating the code

2022-01-11 07:58 UTC, pablomendezroyo commented
> @pablomendezroyo, thanks for contribution!
> 
> Could you undo the changes made for GitHub Pages? We don't need it in this app.
> 
> I also think that it would be better to use the `useDeposit` hook inside your `useDappNodeDeposit` hook instead of duplicating the code

Hi there!

Thank you for the feedback, will remove the gh-pages

I agree there is duplicated code inside `useDappNodeDeposit` and some code from `useDeposit` could be recycled but I am not sure if it worth it. Notice that the `validate` and the `deposit` functions are not the same so these should be implemented and the `useDeposit` hook would become too big.

Another point in favor to keep them separated is to be able to distinguish both hooks (DAppNode and Gnosis)

I just wanted to remark these points, if you still think it is better to mix both hooks I will do it

2022-01-11 14:33 UTC, maxaleks commented on package.json
> +  "homepage": "https://dappnode.github.io/gbc-deposit-ui/",
This change is unnecessary

2022-01-11 14:33 UTC, maxaleks commented on public/index.html
> -    <base href="%PUBLIC_URL%/">
This change is unnecessary

2022-01-11 14:33 UTC, maxaleks commented on package.json
> +  "homepage": "https://dappnode.github.io/gbc-deposit-ui/",
This change is unnecessary

2022-01-11 16:23 UTC, pablomendezroyo commented on public/index.html
> -    <base href="%PUBLIC_URL%/">
removed

2022-01-11 16:23 UTC, pablomendezroyo commented on package.json
> +  "homepage": "https://dappnode.github.io/gbc-deposit-ui/",
fixed

2022-01-11 16:25 UTC, pablomendezroyo commented
@maxaleks there is an env var for the dappnode deposit contract address, included as well in the `.env.example` file. The value is:

 `REACT_APP_DAPPNODE_DEPOSIT_CONTRACT_ADDRESS=0xe9fc19d391dfd5bfadd39c92eab8ae31ef831712`

2022-01-11 16:34 UTC, maxaleks commented
>@maxaleks there is an env var for the dappnode deposit contract address, included as well in the .env.example file. The value is:
>
>REACT_APP_DAPPNODE_DEPOSIT_CONTRACT_ADDRESS=0xe9fc19d391dfd5bfadd39c92eab8ae31ef831712

This address is different from the one you specified in the code. If the old one is in the code, please replace it with the new one

2022-01-11 16:43 UTC, maxaleks commented
I assume that the address in the code is correct

2022-01-11 17:37 UTC, pablomendezroyo commented
> > @maxaleks there is an env var for the dappnode deposit contract address, included as well in the .env.example file. The value is:
> > REACT_APP_DAPPNODE_DEPOSIT_CONTRACT_ADDRESS=0xe9fc19d391dfd5bfadd39c92eab8ae31ef831712
> 
> This address is different from the one you specified in the code. If the old one is in the code, please replace it with the new one

ouch my bad! 

I got confused between the addresses

I confirm the address is 
`0x6C68322cf55f5f025F2aebd93a28761182d077c3`

2022-01-11 17:40 UTC, maxaleks approved these changes

2022-01-11 17:40 UTC, merged